import * as React from 'react';
import Box from '@mui/material/Box';
import CssBaseline from '@mui/material/CssBaseline';
import BottomNavigation from '@mui/material/BottomNavigation';
import BottomNavigationAction from '@mui/material/BottomNavigationAction';
import RestoreIcon from '@mui/icons-material/Restore';
import FavoriteIcon from '@mui/icons-material/Favorite';
import ArchiveIcon from '@mui/icons-material/Archive';
import Paper from '@mui/material/Paper';
import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import ListItemAvatar from '@mui/material/ListItemAvatar';
import ListItemText from '@mui/material/ListItemText';
import Avatar from '@mui/material/Avatar';
import CopyrightIcon from '@mui/icons-material/Copyright';
import { Typography } from '@mui/material';
import FacebookIcon from '@mui/icons-material/Facebook';
import InstagramIcon from '@mui/icons-material/Instagram';
import WhatsAppIcon from '@mui/icons-material/WhatsApp';
// function refreshMessages() {
//   const getRandomInt = (max) => Math.floor(Math.random() * Math.floor(max));

//   return Array.from(new Array(4)).map(
//     () => messageExamples[getRandomInt(messageExamples.length)],
//   );
// }

export default function Footer() {
  const [value, setValue] = React.useState(0);
  const ref = React.useRef(null);
//   const [messages, setMessages] = React.useState(() => refreshMessages());

//   React.useEffect(() => {
//     ref.current.ownerDocument.body.scrollTop = 0;
//     setMessages(refreshMessages());
//   }, [value, setMessages]);

  return (
    <Box sx={{ pb:7 }} ref={ref}>
  
      {/* <List>
        {messages.map(({ primary, secondary, person }, index) => (
          <ListItem button key={index + person}>
            <ListItemAvatar>
              <Avatar alt="Profile Picture" src={person} />
            </ListItemAvatar>
            <ListItemText primary={primary} secondary={secondary} />
          </ListItem>
        ))}
      </List> */}
         <Paper sx={{ position: 'fixed', bottom: 0, left: 0, right: 0, display:"flex", justifyContent:"space between"}} elevation={3}>
              <Typography variant='div' sx={{ mt: 4 }}> <CopyrightIcon /> All Right Reserved</Typography>
              <br/>
                <Typography variant='div'>
                  Social Media
                  <FacebookIcon />
                  <WhatsAppIcon />
                  <InstagramIcon/>
          </Typography>
              </Paper>
        
    </Box>
  );
}

// const messageExamples = [
   
//   {
//     primary: 'Discussion',
//     secondary: `Menus that are generated by the bottom app bar (such as a bottom
//       navigation drawer or overflow menu) open as bottom sheets at a higher elevation
//       than the bar.`,
//     person: '/static/images/avatar/5.jpg',
//   },
//  ];